using Currency.Exchange.Core.DbEntities;
using Microsoft.EntityFrameworkCore;

namespace Currency.Exchange.EntityFramework.Initializer
{
    public class CurrencyExchangeDbInitializer
    {
        private readonly ModelBuilder modelBuilder;

        public CurrencyExchangeDbInitializer(ModelBuilder modelBuilder)
        {
            this.modelBuilder = modelBuilder;
        }

        public void Seed()
        {
            modelBuilder.Entity<CurrencyEntity>().HasData(
                    new CurrencyEntity { Id = 1, Code = "AED", Name = "UAE dirham	", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 2, Code = "AFN", Name = "Afghan afghani", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 3, Code = "ALL", Name = "Albanian lek", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 4, Code = "AMD", Name = "Armenian dram ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 6, Code = "ANG", Name = "Netherlands Antillean guilder ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 7, Code = "AOA", Name = "Angolan kwanza", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 8, Code = "ARS", Name = "Argentine peso", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 9, Code = "AUD", Name = "Australian dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 10, Code = "AWG", Name = "Aruban florin ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 11, Code = "AZN", Name = "Azerbaijan manat", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 12, Code = "BAM", Name = "Bosnia and Herzegovina convertible mark ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 13, Code = "BBD", Name = "Barbadian dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 14, Code = "BDT", Name = "Bangladeshi taka", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 15, Code = "BGN", Name = "Bulgarian lev ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 16, Code = "BHD", Name = "Bahraini dinar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 17, Code = "BIF", Name = "Burundi franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 18, Code = "BMD", Name = "Bermudian dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 19, Code = "BND", Name = "Brunei dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 20, Code = "BOB", Name = "Bolivian boliviano", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 21, Code = "BRL", Name = "Brazilian real", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 22, Code = "BSD", Name = "Bahamian dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 23, Code = "BTN", Name = "Bhutanese ngultrum", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 24, Code = "BWP", Name = "Botswana pula ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 25, Code = "BYN", Name = "Belarusian ruble", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 26, Code = "BZD", Name = "Belize dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 27, Code = "CAD", Name = "Canadian dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 28, Code = "CDF", Name = "Congolese franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 29, Code = "CHF", Name = "Swiss franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 30, Code = "CLP", Name = "Chilean peso", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 31, Code = "CNY", Name = "Chinese Yuan Renminbi ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 32, Code = "COP", Name = "Colombian peso", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 33, Code = "CRC", Name = "Costa Rican colon ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 34, Code = "CUP", Name = "Cuban peso", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 35, Code = "CVE", Name = "Cabo Verdean escudo ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 36, Code = "CZK", Name = "Czech koruna", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 37, Code = "DJF", Name = "Djiboutian franc", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 38, Code = "DKK", Name = "Danish krone", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 39, Code = "DOP", Name = "Dominican peso", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 40, Code = "DZD", Name = "Algerian dinar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 41, Code = "EGP", Name = "Egyptian pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 42, Code = "ERN", Name = "Eritrean nakfa", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 43, Code = "ETB", Name = "Ethiopian birr", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 44, Code = "EUR", Name = "European euro ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 45, Code = "FJD", Name = "Fijian dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 46, Code = "FKP", Name = "Falkland Islands pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 47, Code = "GBP", Name = "Pound sterling", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 48, Code = "GEL", Name = "Georgian lari ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 49, Code = "GGP", Name = "Guernsey Pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 50, Code = "GHS", Name = "Ghanaian cedi ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 51, Code = "GIP", Name = "Gibraltar pound ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 52, Code = "GMD", Name = "Gambian dalasi", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 53, Code = "GNF", Name = "Guinean franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 54, Code = "GTQ", Name = "Guatemalan quetzal", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 55, Code = "GYD", Name = "Guyanese dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 56, Code = "HKD", Name = "Hong Kong dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 57, Code = "HNL", Name = "Honduran lempira", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 58, Code = "HRK", Name = "Croatian kuna ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 59, Code = "HTG", Name = "Haitian gourde", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 60, Code = "HUF", Name = "Hungarian forint", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 61, Code = "IDR", Name = "Indonesian rupiah ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 62, Code = "ILS", Name = "Israeli new shekel", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 63, Code = "ILS", Name = "Israeli new shekel", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 64, Code = "IMP", Name = "Manx pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 65, Code = "INR", Name = "Indian rupee", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 66, Code = "IQD", Name = "Iraqi dinar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 67, Code = "IRR", Name = "Iranian rial", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 68, Code = "ISK", Name = "Icelandic krona ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 69, Code = "JEP", Name = "Jersey pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 70, Code = "JMD", Name = "Jamaican dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 71, Code = "JOD", Name = "Jordanian dinar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 72, Code = "JPY", Name = "Japanese yen", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 73, Code = "KES", Name = "Kenyan shilling ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 74, Code = "KGS", Name = "Kyrgyzstani som ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 75, Code = "KHR", Name = "Cambodian riel", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 76, Code = "KMF", Name = "Comorian franc", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 77, Code = "KPW", Name = "North Korean won", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 78, Code = "KRW", Name = "South Korean won", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 79, Code = "KWD", Name = "Kuwaiti dinar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 80, Code = "KYD", Name = "Cayman Islands dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 81, Code = "KZT", Name = "Kazakhstani tenge ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 82, Code = "LAK", Name = "Lao kip ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 83, Code = "LBP", Name = "Lebanese pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 84, Code = "LKR", Name = "Sri Lankan rupee", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 85, Code = "LRD", Name = "Liberian dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 86, Code = "LSL", Name = "Lesotho loti", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 87, Code = "LYD", Name = "Libyan dinar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 88, Code = "MAD", Name = "Moroccan dirham ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 89, Code = "MDL", Name = "Moldovan leu", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 90, Code = "MGA", Name = "Malagasy ariary ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 91, Code = "MKD", Name = "Macedonian denar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 92, Code = "MMK", Name = "Myanmar kyat", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 93, Code = "MNT", Name = "Mongolian tugrik", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 94, Code = "MOP", Name = "Macanese pataca ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 95, Code = "MRU", Name = "Mauritanian ouguiya ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 96, Code = "MUR", Name = "Mauritian rupee ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 97, Code = "MVR", Name = "Maldivian rufiyaa ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 98, Code = "MWK", Name = "Malawian kwacha ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 99, Code = "MXN", Name = "Mexican peso", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 100, Code = "MYR", Name = "Malaysian ringgit ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 101, Code = "MZN", Name = "Mozambican metical", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 102, Code = "NAD", Name = "Namibian dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 103, Code = "NGN", Name = "Nigerian naira", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 104, Code = "NIO", Name = "Nicaraguan cordoba", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 105, Code = "NOK", Name = "Norwegian krone ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 106, Code = "NOK", Name = "Norwegian krone ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 109, Code = "NPR", Name = "Nepalese rupee", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 110, Code = "NZD", Name = "New Zealand dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 111, Code = "OMR", Name = "Omani rial", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 112, Code = "PEN", Name = "Peruvian sol", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 113, Code = "PGK", Name = "Papua New Guinean kina", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 114, Code = "PHP", Name = "Philippine peso ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 115, Code = "PKR", Name = "Pakistani rupee ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 116, Code = "PLN", Name = "Polish zloty", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 117, Code = "PYG", Name = "Paraguayan guarani", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 118, Code = "RSD", Name = "Serbian dinar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 119, Code = "RUB", Name = "Russian ruble ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 120, Code = "RWF", Name = "Rwandan franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 121, Code = "SAR", Name = "Saudi Arabian riyal ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 122, Code = "SBD", Name = "Solomon Islands dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 123, Code = "SCR", Name = "Seychellois rupee ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 124, Code = "SDG", Name = "Sudanese pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 125, Code = "SEK", Name = "Swedish krona ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 126, Code = "SGD", Name = "Singapore dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 127, Code = "SHP", Name = "Saint Helena pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 128, Code = "SLL", Name = "Sierra Leonean leone", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 129, Code = "SOS", Name = "Somali shilling ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 130, Code = "SRD", Name = "Surinamese dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 131, Code = "SSP", Name = "South Sudanese pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 132, Code = "STN", Name = "Sao Tome and Principe dobra ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 133, Code = "SYP", Name = "Syrian pound", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 134, Code = "SZL", Name = "Swazi lilangeni ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 135, Code = "TJS", Name = "Tajikistani somoni", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 136, Code = "TMT", Name = "Turkmen manat ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 137, Code = "TND", Name = "Tunisian dinar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 138, Code = "TOP", Name = "Tongan pa’anga", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 139, Code = "TRY", Name = "Turkish lira", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 140, Code = "TTD", Name = "Trinidad and Tobago dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 141, Code = "TWD", Name = "New Taiwan dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 142, Code = "TZS", Name = "Tanzanian shilling", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 143, Code = "UAH", Name = "Ukrainian hryvnia ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 144, Code = "USD", Name = "United States dollar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 145, Code = "UZS", Name = "Uzbekistani som ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 146, Code = "VES", Name = "Venezuelan bolivar", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 147, Code = "VND", Name = "Vietnamese dong ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 148, Code = "VUV", Name = "Vanuatu vatu", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 149, Code = "WST", Name = "Samoan tala ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 150, Code = "XAF", Name = "Central African CFA franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 151, Code = "XCD", Name = "East Caribbean dollar ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 152, Code = "XDR", Name = "SDR (Special Drawing Right) ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 153, Code = "XOF", Name = "West African CFA franc", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 154, Code = "XPF", Name = "CFP franc ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 155, Code = "YER", Name = "Yemeni rial ", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 156, Code = "ZAR", Name = "South African rand", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false },
                    new CurrencyEntity { Id = 157, Code = "ZMW", Name = "Zambian kwacha", CreatedBy = "1", CreatedOn = DateTime.Now, IsDeleted = false }

                );
            
        }
    }
}
