// <auto-generated />
using System;
using Currency.Exchange.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Currency.Exchange.EntityFramework.Migrations.CurrencyExchangeDb
{
    [DbContext(typeof(CurrencyExchangeDbContext))]
    [Migration("20221019212642_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Currency.Exchange.Core.DbEntities.CurrencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AED",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9804),
                            IsDeleted = false,
                            Name = "UAE dirham	"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AFN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9812),
                            IsDeleted = false,
                            Name = "Afghan afghani"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ALL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9813),
                            IsDeleted = false,
                            Name = "Albanian lek"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AMD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9815),
                            IsDeleted = false,
                            Name = "Armenian dram "
                        },
                        new
                        {
                            Id = 6,
                            Code = "ANG",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9816),
                            IsDeleted = false,
                            Name = "Netherlands Antillean guilder "
                        },
                        new
                        {
                            Id = 7,
                            Code = "AOA",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9817),
                            IsDeleted = false,
                            Name = "Angolan kwanza"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ARS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9818),
                            IsDeleted = false,
                            Name = "Argentine peso"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AUD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9820),
                            IsDeleted = false,
                            Name = "Australian dollar "
                        },
                        new
                        {
                            Id = 10,
                            Code = "AWG",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9821),
                            IsDeleted = false,
                            Name = "Aruban florin "
                        },
                        new
                        {
                            Id = 11,
                            Code = "AZN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9822),
                            IsDeleted = false,
                            Name = "Azerbaijan manat"
                        },
                        new
                        {
                            Id = 12,
                            Code = "BAM",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9823),
                            IsDeleted = false,
                            Name = "Bosnia and Herzegovina convertible mark "
                        },
                        new
                        {
                            Id = 13,
                            Code = "BBD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9824),
                            IsDeleted = false,
                            Name = "Barbadian dollar"
                        },
                        new
                        {
                            Id = 14,
                            Code = "BDT",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9826),
                            IsDeleted = false,
                            Name = "Bangladeshi taka"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BGN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9827),
                            IsDeleted = false,
                            Name = "Bulgarian lev "
                        },
                        new
                        {
                            Id = 16,
                            Code = "BHD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9828),
                            IsDeleted = false,
                            Name = "Bahraini dinar"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BIF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9829),
                            IsDeleted = false,
                            Name = "Burundi franc "
                        },
                        new
                        {
                            Id = 18,
                            Code = "BMD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9830),
                            IsDeleted = false,
                            Name = "Bermudian dollar"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BND",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9832),
                            IsDeleted = false,
                            Name = "Brunei dollar "
                        },
                        new
                        {
                            Id = 20,
                            Code = "BOB",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9833),
                            IsDeleted = false,
                            Name = "Bolivian boliviano"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BRL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9834),
                            IsDeleted = false,
                            Name = "Brazilian real"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BSD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9835),
                            IsDeleted = false,
                            Name = "Bahamian dollar "
                        },
                        new
                        {
                            Id = 23,
                            Code = "BTN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9837),
                            IsDeleted = false,
                            Name = "Bhutanese ngultrum"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BWP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9838),
                            IsDeleted = false,
                            Name = "Botswana pula "
                        },
                        new
                        {
                            Id = 25,
                            Code = "BYN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9839),
                            IsDeleted = false,
                            Name = "Belarusian ruble"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BZD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9840),
                            IsDeleted = false,
                            Name = "Belize dollar "
                        },
                        new
                        {
                            Id = 27,
                            Code = "CAD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9841),
                            IsDeleted = false,
                            Name = "Canadian dollar "
                        },
                        new
                        {
                            Id = 28,
                            Code = "CDF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9843),
                            IsDeleted = false,
                            Name = "Congolese franc "
                        },
                        new
                        {
                            Id = 29,
                            Code = "CHF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9844),
                            IsDeleted = false,
                            Name = "Swiss franc "
                        },
                        new
                        {
                            Id = 30,
                            Code = "CLP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9845),
                            IsDeleted = false,
                            Name = "Chilean peso"
                        },
                        new
                        {
                            Id = 31,
                            Code = "CNY",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9846),
                            IsDeleted = false,
                            Name = "Chinese Yuan Renminbi "
                        },
                        new
                        {
                            Id = 32,
                            Code = "COP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9847),
                            IsDeleted = false,
                            Name = "Colombian peso"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CRC",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9849),
                            IsDeleted = false,
                            Name = "Costa Rican colon "
                        },
                        new
                        {
                            Id = 34,
                            Code = "CUP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9850),
                            IsDeleted = false,
                            Name = "Cuban peso"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CVE",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9851),
                            IsDeleted = false,
                            Name = "Cabo Verdean escudo "
                        },
                        new
                        {
                            Id = 36,
                            Code = "CZK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9852),
                            IsDeleted = false,
                            Name = "Czech koruna"
                        },
                        new
                        {
                            Id = 37,
                            Code = "DJF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9853),
                            IsDeleted = false,
                            Name = "Djiboutian franc"
                        },
                        new
                        {
                            Id = 38,
                            Code = "DKK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9855),
                            IsDeleted = false,
                            Name = "Danish krone"
                        },
                        new
                        {
                            Id = 39,
                            Code = "DOP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9856),
                            IsDeleted = false,
                            Name = "Dominican peso"
                        },
                        new
                        {
                            Id = 40,
                            Code = "DZD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9857),
                            IsDeleted = false,
                            Name = "Algerian dinar"
                        },
                        new
                        {
                            Id = 41,
                            Code = "EGP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9858),
                            IsDeleted = false,
                            Name = "Egyptian pound"
                        },
                        new
                        {
                            Id = 42,
                            Code = "ERN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9859),
                            IsDeleted = false,
                            Name = "Eritrean nakfa"
                        },
                        new
                        {
                            Id = 43,
                            Code = "ETB",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9861),
                            IsDeleted = false,
                            Name = "Ethiopian birr"
                        },
                        new
                        {
                            Id = 44,
                            Code = "EUR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9862),
                            IsDeleted = false,
                            Name = "European euro "
                        },
                        new
                        {
                            Id = 45,
                            Code = "FJD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9863),
                            IsDeleted = false,
                            Name = "Fijian dollar "
                        },
                        new
                        {
                            Id = 46,
                            Code = "FKP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9864),
                            IsDeleted = false,
                            Name = "Falkland Islands pound"
                        },
                        new
                        {
                            Id = 47,
                            Code = "GBP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9865),
                            IsDeleted = false,
                            Name = "Pound sterling"
                        },
                        new
                        {
                            Id = 48,
                            Code = "GEL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9867),
                            IsDeleted = false,
                            Name = "Georgian lari "
                        },
                        new
                        {
                            Id = 49,
                            Code = "GGP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9868),
                            IsDeleted = false,
                            Name = "Guernsey Pound"
                        },
                        new
                        {
                            Id = 50,
                            Code = "GHS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9869),
                            IsDeleted = false,
                            Name = "Ghanaian cedi "
                        },
                        new
                        {
                            Id = 51,
                            Code = "GIP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9870),
                            IsDeleted = false,
                            Name = "Gibraltar pound "
                        },
                        new
                        {
                            Id = 52,
                            Code = "GMD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9871),
                            IsDeleted = false,
                            Name = "Gambian dalasi"
                        },
                        new
                        {
                            Id = 53,
                            Code = "GNF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9872),
                            IsDeleted = false,
                            Name = "Guinean franc "
                        },
                        new
                        {
                            Id = 54,
                            Code = "GTQ",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9874),
                            IsDeleted = false,
                            Name = "Guatemalan quetzal"
                        },
                        new
                        {
                            Id = 55,
                            Code = "GYD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9875),
                            IsDeleted = false,
                            Name = "Guyanese dollar "
                        },
                        new
                        {
                            Id = 56,
                            Code = "HKD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9876),
                            IsDeleted = false,
                            Name = "Hong Kong dollar"
                        },
                        new
                        {
                            Id = 57,
                            Code = "HNL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9877),
                            IsDeleted = false,
                            Name = "Honduran lempira"
                        },
                        new
                        {
                            Id = 58,
                            Code = "HRK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9878),
                            IsDeleted = false,
                            Name = "Croatian kuna "
                        },
                        new
                        {
                            Id = 59,
                            Code = "HTG",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9880),
                            IsDeleted = false,
                            Name = "Haitian gourde"
                        },
                        new
                        {
                            Id = 60,
                            Code = "HUF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9881),
                            IsDeleted = false,
                            Name = "Hungarian forint"
                        },
                        new
                        {
                            Id = 61,
                            Code = "IDR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9882),
                            IsDeleted = false,
                            Name = "Indonesian rupiah "
                        },
                        new
                        {
                            Id = 62,
                            Code = "ILS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9883),
                            IsDeleted = false,
                            Name = "Israeli new shekel"
                        },
                        new
                        {
                            Id = 63,
                            Code = "ILS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9884),
                            IsDeleted = false,
                            Name = "Israeli new shekel"
                        },
                        new
                        {
                            Id = 64,
                            Code = "IMP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9886),
                            IsDeleted = false,
                            Name = "Manx pound"
                        },
                        new
                        {
                            Id = 65,
                            Code = "INR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9887),
                            IsDeleted = false,
                            Name = "Indian rupee"
                        },
                        new
                        {
                            Id = 66,
                            Code = "IQD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9888),
                            IsDeleted = false,
                            Name = "Iraqi dinar "
                        },
                        new
                        {
                            Id = 67,
                            Code = "IRR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9889),
                            IsDeleted = false,
                            Name = "Iranian rial"
                        },
                        new
                        {
                            Id = 68,
                            Code = "ISK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9890),
                            IsDeleted = false,
                            Name = "Icelandic krona "
                        },
                        new
                        {
                            Id = 69,
                            Code = "JEP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9892),
                            IsDeleted = false,
                            Name = "Jersey pound"
                        },
                        new
                        {
                            Id = 70,
                            Code = "JMD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9893),
                            IsDeleted = false,
                            Name = "Jamaican dollar "
                        },
                        new
                        {
                            Id = 71,
                            Code = "JOD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9922),
                            IsDeleted = false,
                            Name = "Jordanian dinar "
                        },
                        new
                        {
                            Id = 72,
                            Code = "JPY",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9923),
                            IsDeleted = false,
                            Name = "Japanese yen"
                        },
                        new
                        {
                            Id = 73,
                            Code = "KES",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9924),
                            IsDeleted = false,
                            Name = "Kenyan shilling "
                        },
                        new
                        {
                            Id = 74,
                            Code = "KGS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9925),
                            IsDeleted = false,
                            Name = "Kyrgyzstani som "
                        },
                        new
                        {
                            Id = 75,
                            Code = "KHR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9927),
                            IsDeleted = false,
                            Name = "Cambodian riel"
                        },
                        new
                        {
                            Id = 76,
                            Code = "KMF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9928),
                            IsDeleted = false,
                            Name = "Comorian franc"
                        },
                        new
                        {
                            Id = 77,
                            Code = "KPW",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9929),
                            IsDeleted = false,
                            Name = "North Korean won"
                        },
                        new
                        {
                            Id = 78,
                            Code = "KRW",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9930),
                            IsDeleted = false,
                            Name = "South Korean won"
                        },
                        new
                        {
                            Id = 79,
                            Code = "KWD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9931),
                            IsDeleted = false,
                            Name = "Kuwaiti dinar "
                        },
                        new
                        {
                            Id = 80,
                            Code = "KYD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9932),
                            IsDeleted = false,
                            Name = "Cayman Islands dollar "
                        },
                        new
                        {
                            Id = 81,
                            Code = "KZT",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9934),
                            IsDeleted = false,
                            Name = "Kazakhstani tenge "
                        },
                        new
                        {
                            Id = 82,
                            Code = "LAK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9935),
                            IsDeleted = false,
                            Name = "Lao kip "
                        },
                        new
                        {
                            Id = 83,
                            Code = "LBP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9936),
                            IsDeleted = false,
                            Name = "Lebanese pound"
                        },
                        new
                        {
                            Id = 84,
                            Code = "LKR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9937),
                            IsDeleted = false,
                            Name = "Sri Lankan rupee"
                        },
                        new
                        {
                            Id = 85,
                            Code = "LRD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9938),
                            IsDeleted = false,
                            Name = "Liberian dollar "
                        },
                        new
                        {
                            Id = 86,
                            Code = "LSL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9939),
                            IsDeleted = false,
                            Name = "Lesotho loti"
                        },
                        new
                        {
                            Id = 87,
                            Code = "LYD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9941),
                            IsDeleted = false,
                            Name = "Libyan dinar"
                        },
                        new
                        {
                            Id = 88,
                            Code = "MAD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9942),
                            IsDeleted = false,
                            Name = "Moroccan dirham "
                        },
                        new
                        {
                            Id = 89,
                            Code = "MDL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9943),
                            IsDeleted = false,
                            Name = "Moldovan leu"
                        },
                        new
                        {
                            Id = 90,
                            Code = "MGA",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9944),
                            IsDeleted = false,
                            Name = "Malagasy ariary "
                        },
                        new
                        {
                            Id = 91,
                            Code = "MKD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9945),
                            IsDeleted = false,
                            Name = "Macedonian denar"
                        },
                        new
                        {
                            Id = 92,
                            Code = "MMK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9946),
                            IsDeleted = false,
                            Name = "Myanmar kyat"
                        },
                        new
                        {
                            Id = 93,
                            Code = "MNT",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9948),
                            IsDeleted = false,
                            Name = "Mongolian tugrik"
                        },
                        new
                        {
                            Id = 94,
                            Code = "MOP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9949),
                            IsDeleted = false,
                            Name = "Macanese pataca "
                        },
                        new
                        {
                            Id = 95,
                            Code = "MRU",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9950),
                            IsDeleted = false,
                            Name = "Mauritanian ouguiya "
                        },
                        new
                        {
                            Id = 96,
                            Code = "MUR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9951),
                            IsDeleted = false,
                            Name = "Mauritian rupee "
                        },
                        new
                        {
                            Id = 97,
                            Code = "MVR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9952),
                            IsDeleted = false,
                            Name = "Maldivian rufiyaa "
                        },
                        new
                        {
                            Id = 98,
                            Code = "MWK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9954),
                            IsDeleted = false,
                            Name = "Malawian kwacha "
                        },
                        new
                        {
                            Id = 99,
                            Code = "MXN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9955),
                            IsDeleted = false,
                            Name = "Mexican peso"
                        },
                        new
                        {
                            Id = 100,
                            Code = "MYR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9956),
                            IsDeleted = false,
                            Name = "Malaysian ringgit "
                        },
                        new
                        {
                            Id = 101,
                            Code = "MZN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9957),
                            IsDeleted = false,
                            Name = "Mozambican metical"
                        },
                        new
                        {
                            Id = 102,
                            Code = "NAD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9958),
                            IsDeleted = false,
                            Name = "Namibian dollar "
                        },
                        new
                        {
                            Id = 103,
                            Code = "NGN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9960),
                            IsDeleted = false,
                            Name = "Nigerian naira"
                        },
                        new
                        {
                            Id = 104,
                            Code = "NIO",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9961),
                            IsDeleted = false,
                            Name = "Nicaraguan cordoba"
                        },
                        new
                        {
                            Id = 105,
                            Code = "NOK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9962),
                            IsDeleted = false,
                            Name = "Norwegian krone "
                        },
                        new
                        {
                            Id = 106,
                            Code = "NOK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9963),
                            IsDeleted = false,
                            Name = "Norwegian krone "
                        },
                        new
                        {
                            Id = 109,
                            Code = "NPR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9964),
                            IsDeleted = false,
                            Name = "Nepalese rupee"
                        },
                        new
                        {
                            Id = 110,
                            Code = "NZD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9965),
                            IsDeleted = false,
                            Name = "New Zealand dollar"
                        },
                        new
                        {
                            Id = 111,
                            Code = "OMR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9967),
                            IsDeleted = false,
                            Name = "Omani rial"
                        },
                        new
                        {
                            Id = 112,
                            Code = "PEN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9968),
                            IsDeleted = false,
                            Name = "Peruvian sol"
                        },
                        new
                        {
                            Id = 113,
                            Code = "PGK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9969),
                            IsDeleted = false,
                            Name = "Papua New Guinean kina"
                        },
                        new
                        {
                            Id = 114,
                            Code = "PHP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9970),
                            IsDeleted = false,
                            Name = "Philippine peso "
                        },
                        new
                        {
                            Id = 115,
                            Code = "PKR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9971),
                            IsDeleted = false,
                            Name = "Pakistani rupee "
                        },
                        new
                        {
                            Id = 116,
                            Code = "PLN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9973),
                            IsDeleted = false,
                            Name = "Polish zloty"
                        },
                        new
                        {
                            Id = 117,
                            Code = "PYG",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9974),
                            IsDeleted = false,
                            Name = "Paraguayan guarani"
                        },
                        new
                        {
                            Id = 118,
                            Code = "RSD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9975),
                            IsDeleted = false,
                            Name = "Serbian dinar "
                        },
                        new
                        {
                            Id = 119,
                            Code = "RUB",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9976),
                            IsDeleted = false,
                            Name = "Russian ruble "
                        },
                        new
                        {
                            Id = 120,
                            Code = "RWF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9977),
                            IsDeleted = false,
                            Name = "Rwandan franc "
                        },
                        new
                        {
                            Id = 121,
                            Code = "SAR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9978),
                            IsDeleted = false,
                            Name = "Saudi Arabian riyal "
                        },
                        new
                        {
                            Id = 122,
                            Code = "SBD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9980),
                            IsDeleted = false,
                            Name = "Solomon Islands dollar"
                        },
                        new
                        {
                            Id = 123,
                            Code = "SCR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9981),
                            IsDeleted = false,
                            Name = "Seychellois rupee "
                        },
                        new
                        {
                            Id = 124,
                            Code = "SDG",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9982),
                            IsDeleted = false,
                            Name = "Sudanese pound"
                        },
                        new
                        {
                            Id = 125,
                            Code = "SEK",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9983),
                            IsDeleted = false,
                            Name = "Swedish krona "
                        },
                        new
                        {
                            Id = 126,
                            Code = "SGD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9984),
                            IsDeleted = false,
                            Name = "Singapore dollar"
                        },
                        new
                        {
                            Id = 127,
                            Code = "SHP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9986),
                            IsDeleted = false,
                            Name = "Saint Helena pound"
                        },
                        new
                        {
                            Id = 128,
                            Code = "SLL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9987),
                            IsDeleted = false,
                            Name = "Sierra Leonean leone"
                        },
                        new
                        {
                            Id = 129,
                            Code = "SOS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9988),
                            IsDeleted = false,
                            Name = "Somali shilling "
                        },
                        new
                        {
                            Id = 130,
                            Code = "SRD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9989),
                            IsDeleted = false,
                            Name = "Surinamese dollar "
                        },
                        new
                        {
                            Id = 131,
                            Code = "SSP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9990),
                            IsDeleted = false,
                            Name = "South Sudanese pound"
                        },
                        new
                        {
                            Id = 132,
                            Code = "STN",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9992),
                            IsDeleted = false,
                            Name = "Sao Tome and Principe dobra "
                        },
                        new
                        {
                            Id = 133,
                            Code = "SYP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9993),
                            IsDeleted = false,
                            Name = "Syrian pound"
                        },
                        new
                        {
                            Id = 134,
                            Code = "SZL",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9994),
                            IsDeleted = false,
                            Name = "Swazi lilangeni "
                        },
                        new
                        {
                            Id = 135,
                            Code = "TJS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9995),
                            IsDeleted = false,
                            Name = "Tajikistani somoni"
                        },
                        new
                        {
                            Id = 136,
                            Code = "TMT",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9996),
                            IsDeleted = false,
                            Name = "Turkmen manat "
                        },
                        new
                        {
                            Id = 137,
                            Code = "TND",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9997),
                            IsDeleted = false,
                            Name = "Tunisian dinar"
                        },
                        new
                        {
                            Id = 138,
                            Code = "TOP",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 919, DateTimeKind.Local).AddTicks(9998),
                            IsDeleted = false,
                            Name = "Tongan pa’anga"
                        },
                        new
                        {
                            Id = 139,
                            Code = "TRY",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Turkish lira"
                        },
                        new
                        {
                            Id = 140,
                            Code = "TTD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(1),
                            IsDeleted = false,
                            Name = "Trinidad and Tobago dollar"
                        },
                        new
                        {
                            Id = 141,
                            Code = "TWD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(2),
                            IsDeleted = false,
                            Name = "New Taiwan dollar "
                        },
                        new
                        {
                            Id = 142,
                            Code = "TZS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(3),
                            IsDeleted = false,
                            Name = "Tanzanian shilling"
                        },
                        new
                        {
                            Id = 143,
                            Code = "UAH",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(4),
                            IsDeleted = false,
                            Name = "Ukrainian hryvnia "
                        },
                        new
                        {
                            Id = 144,
                            Code = "USD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(5),
                            IsDeleted = false,
                            Name = "United States dollar"
                        },
                        new
                        {
                            Id = 145,
                            Code = "UZS",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(7),
                            IsDeleted = false,
                            Name = "Uzbekistani som "
                        },
                        new
                        {
                            Id = 146,
                            Code = "VES",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(8),
                            IsDeleted = false,
                            Name = "Venezuelan bolivar"
                        },
                        new
                        {
                            Id = 147,
                            Code = "VND",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(9),
                            IsDeleted = false,
                            Name = "Vietnamese dong "
                        },
                        new
                        {
                            Id = 148,
                            Code = "VUV",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(10),
                            IsDeleted = false,
                            Name = "Vanuatu vatu"
                        },
                        new
                        {
                            Id = 149,
                            Code = "WST",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(11),
                            IsDeleted = false,
                            Name = "Samoan tala "
                        },
                        new
                        {
                            Id = 150,
                            Code = "XAF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(12),
                            IsDeleted = false,
                            Name = "Central African CFA franc "
                        },
                        new
                        {
                            Id = 151,
                            Code = "XCD",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(14),
                            IsDeleted = false,
                            Name = "East Caribbean dollar "
                        },
                        new
                        {
                            Id = 152,
                            Code = "XDR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(15),
                            IsDeleted = false,
                            Name = "SDR (Special Drawing Right) "
                        },
                        new
                        {
                            Id = 153,
                            Code = "XOF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(16),
                            IsDeleted = false,
                            Name = "West African CFA franc"
                        },
                        new
                        {
                            Id = 154,
                            Code = "XPF",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(17),
                            IsDeleted = false,
                            Name = "CFP franc "
                        },
                        new
                        {
                            Id = 155,
                            Code = "YER",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(18),
                            IsDeleted = false,
                            Name = "Yemeni rial "
                        },
                        new
                        {
                            Id = 156,
                            Code = "ZAR",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(20),
                            IsDeleted = false,
                            Name = "South African rand"
                        },
                        new
                        {
                            Id = 157,
                            Code = "ZMW",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2022, 10, 20, 0, 26, 41, 920, DateTimeKind.Local).AddTicks(21),
                            IsDeleted = false,
                            Name = "Zambian kwacha"
                        });
                });

            modelBuilder.Entity("Currency.Exchange.Core.DbEntities.ExchangeRateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
